name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    runs-on: windows-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - run: MSBuild -ver
    - run: cd ${{ github.workspace }}/prog3
    - name: Run MSBuild
      run: msbuild -m ${{ github.workspace }}/prog3/боота.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
          name: Build
          path: x64/Debug/боота.exe

