name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    runs-on: windows-latest
    steps:
    - name: clone repo
      uses: action/checkout@v2
    - name: run
    - run: cd ${{ github.workspace }}
    - run: cmake 0.cpp
      
